controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    water_pump_cont:
      type: position_controllers/JointPositionController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link
    
    # Four wheel drive configuration - treating as skid steer
    left_wheel_names: ['front_left_wheel_joint', 'rear_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'rear_right_wheel_joint']
    
    wheel_separation: 0.45
    wheel_radius: 0.08

    use_stamped_vel: false

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: false
        max_velocity: 0.5
    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: false
        max_velocity: 1.0

    # Publishing
    publish_rate: 50.0
    publish_wheel_data: true
    publish_odom: true
    publish_odom_tf: true
    
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

water_pump_cont:
  ros__parameters:
    joint: water_pump_joint

joint_broad:
  ros__parameters: