controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link

    # For 4-wheel configuration, we specify multiple wheels per side
    left_wheel_names: ['left_front_wheel_joint', 'left_rear_wheel_joint']
    right_wheel_names: ['right_front_wheel_joint', 'right_rear_wheel_joint']
    
    # Increase wheels_per_side to 2 for 4-wheel robot
    wheels_per_side: 2
    
    wheel_separation: 0.35
    wheel_radius: 0.05

    use_stamped_vel: false

    # Set wheel separation multiplier to 1.0 for better stability
    wheel_separation_multiplier: 1.0

    # Set wheel radius multiplier to 1.0 for accurate movement
    wheel_radius_multiplier: 1.0

    # Publish to TF
    enable_odom_tf: true

    # Odometry
    publish_odom: true
    publish_wheel_odom: false

    odom_frame_id: odom
    
    # Covariance values
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    # Set publish_cmd to true to publish cmd_vel_out
    publish_cmd: true

    # Velocity and acceleration limits
    cmd_vel_timeout: 0.5
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0